### ISSUE TITLE
Using typescript in an existing adonis v4 app

### ISSUE THREAD

**Issue by wahaaabello** [adonisjs-community/create-adonis-ts-app#26]
Hello

I'd like to begin using typescript in an existing adonis v4 app and I'm not sure how to go about.

Any help would be appreciated.

**Comment by RomainLanz** [comment]
Hey @wahaaabello! 👋 

AdonisJS 4 was not designed to work with TypeScript.
Upgrade to AdonisJS 5 if you want to use TypeScript inside your project.
