### ISSUE TITLE
new project and get some error?

### ISSUE THREAD

**Issue by southorange1228** [adonisjs-community/create-adonis-ts-app#27]
when i use command `npm init adonis-ts-app hello-world --debug` to new prpject, i get some error?
![image](https://user-images.githubusercontent.com/32590310/119069707-3751f980-ba19-11eb-8ba7-a10378d7e0a4.png)

node version: v14.17.0

npm version: 6.14.13

what should i do? thanks:)

**Comment by RomainLanz** [comment]
Hey @southorange1228! 👋 

Can you please try with the following?

```shell
npm init adonis-ts-app@latest hello-world
```

📚 https://docs.adonisjs.com/guides/installation#creating-a-new-project

**Comment by southorange1228** [comment]
@RomainLanz 
i just run the shell code 
```shell
npm init adonis-ts-app@latest hello-world --debug
```
and then i got the same error. it always seems to be missing some packages. 0.0
![image](https://user-images.githubusercontent.com/32590310/119180217-96a81c00-baa2-11eb-851d-4dd4bdac0dc1.png)

**Comment by southorange1228** [comment]
wow, i'm succeded when i use `yarn` and shell code.
```shell
yarn create adonis-ts-app hello-world --debug
```
![image](https://user-images.githubusercontent.com/32590310/119181461-36b27500-baa4-11eb-97bf-9f49c59777c4.png)


but why did i get some error when i use `npm`，that is something I can't understand.

**Comment by RomainLanz** [comment]
Great! Maybe you have a special configuration for `npm`.
I am closing this issue since it works with `yarn`!
