### ISSUE TITLE
Cannot create new app with either yarn or npm

### ISSUE THREAD

**Issue by richardweaver** [adonisjs-community/create-adonis-ts-app#31]
## Package version
4.02

## Node.js and npm version
node 14.5.0
npm 6.14.5
yarn 1.22.10

## Sample Code (to reproduce the issue)
I've tried to create a new app with both yarn and npm and get the same issue:
`Package subpath './package.json' is not defined by "exports" in /Users/richard_weaver/Projects/enotria-adonisjs/node_modules/@adonisjs/core/package.json`

## BONUS (a sample repo to reproduce the issue)
<img width="564" alt="Screenshot 2021-07-16 at 11 03 56" src="https://user-images.githubusercontent.com/56024126/125931429-ba409897-2dbf-4b15-acf2-68400d3068ab.png">

**Comment by RomainLanz** [comment]
Hey @richardweaver! 👋 

Please, update your Node.js version.

**Comment by richardweaver** [comment]
🤦 I missed the sysreqs! My bad, thanks @RomainLanz, all working now.

**Comment by Tjoosten** [comment]
Got the same problem 

Node version: v14.8.0
Npm version: 7.20.2

**Comment by richardweaver** [comment]
@Tjoosten It's the same issue - your Node is out of date. Latest is 14.17.
