### ISSUE TITLE
npm `start` script has wrong file path

### ISSUE THREAD

**Issue by cawa-93** [adonisjs-community/create-adonis-ts-app#36]
After generating the project, a `start` script is created: `node server.js` But this leads to an error because the target file is in the `build` subdirectory: `node build/server.js`

## Node.js and npm version
16/13 and 8.1

**Comment by RomainLanz** [comment]
Hey @cawa-93! 👋🏻 

This is expected, you should only publish the file under `build` directory.
Therefore, the path is correct within it.
