### ISSUE TITLE
README typo (CLI param example)

### ISSUE THREAD

**Issue by nikitazdvijkov** [adonisjs-community/create-adonis-ts-app#39]
In the README, the `name` parameter example says `--boilerplate=my-app` where it should say `--name=my-app`.

As it is, in full:

```
npm init adonis-ts-app hello-world -- --boilerplate=my-app
```

As it should be:

```
npm init adonis-ts-app hello-world -- --name=my-app
```

**Comment by thetutlage** [comment]
Can you please send a PR to fix it?
