### ISSUE TITLE
Installing with "yarn create" adds both a package-lock.json and yarn.lock

### ISSUE THREAD

**Issue by soren121** [adonisjs-community/create-adonis-ts-app#46]
This is a minor issue, but a curious one. I wouldn't expect an NPM lock file to be made while installing with Yarn, and Yarn will also complain if you try to install dependencies while a package-lock.json exists in the same directory.

## Package version
4.2.0

## Node.js and npm version
Node.js 16.16.0
npm 8.1.1
yarn 1.22.19

## Sample Code (to reproduce the issue)
1. Run `yarn create adonis-ts-app hello-world` as described in the [Adonis install docs](https://docs.adonisjs.com/guides/installation#creating-a-new-project).
2. Observe that it creates both a package-lock.json and yarn.lock in the hello-world directory.

**Comment by thetutlage** [comment]
Hello! 

Thanks for reporting the issue. I can confirm that indeed both `npm` and `yarn` are getting used to install dependencies.

**Comment by thetutlage** [comment]
Should be all good with version `4.2.2`.
