### ISSUE TITLE
Dependencies error @symfony/webpack-encore

### ISSUE THREAD

**Issue by bladerangel** [adonisjs-community/create-adonis-ts-app#48]
## Package version
Latest at 21 September 2022

## Versions
 Node: 14.17.3
 Npm: 6.14.13

## Commands
```
npm init adonis-ts-app@latest hello-world
```
> Select the project structure · web
> Enter the project name · hello-world
> Setup eslint? (y/N) · false
> Configure webpack encore for compiling frontend assets? (y/N) · true
```
node ace serve --watch
```

## Error
```
[ encore ] internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '@babel/core'
Require stack:
- node_modules\@symfony\webpack-encore\lib\config\parse-runtime.js
```

## Dependencies
`"@symfony/webpack-encore": "^4.0.0"`

## Solution
```
npm install webpack webpack-cli @babel/core @babel/preset-env --save-dev
```
> [4.0! Goodbye "peer dependency" Warnings](https://github.com/symfony/webpack-encore/releases/tag/v4.0.0)

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/assembler/releases/tag/v5.9.0
